version: '3.7'

services:
  store-db:
    image: postgis/postgis:14-master
    container_name: store-db
    ports:
      - "5422:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stores_db
